# Generated by Django 5.0.1 on 2026-02-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Roll No / Employee ID', max_length=50, null=True, unique=True),
        ),
    ]
